### ISSUE TITLE
[Line Timetable ] upload models and assignation

### ISSUE THREAD

**Issue by bbonnesoeur** [CanalTP/MttBundle#58]
As an admin I  can upload a model for line time table in order to assign it to a line.

**Tasks**
1. handle line timecard Archive
  - update database in order to manage stop time table and line timetable
  - handle the new format (archive) (Entity : _template/layout-template/template_)
2. Assign model to a line
  - Add a "Line Time Table" Menu Item. (handle it with a new permission)
  - Assignment form

**Acceptance tests**
1.New Model archive can be uploaded.

GIVEN I'm connected as an Admin and I'm in "Administration > Ajouter / Mettre à jour les modèles"

WHEN I click on "Ajouter un modèle"

AND I upload the new model archive

THEN the new model is accepted

AND the new model is available in the "Gestion des modèles" list

 
---
This following acceptance test will be effective after this issue #58

2. New Model archive can be updated
GIVEN I'm connected as an Admin and I'm in "Administration > Ajouter / Mettre à jour les modèles"

WHEN I have a old model already uploaded

AND I click on "Mettre à jour"

AND I upload a new model

THEN the new model is accepted

AND the previous old model is replaced by the new one

---

3. New Model archive appears in the assignation page

GIVEN I'm connected as an Admin and I'm in "Administration > Assigner les modèles au client"

WHEN I click on "Assigner"

THEN modal "Assigner" pops up

AND the new uploaded model appears in the list

4. New Model archive assigned to client

GIVEN modal "Assigner" is open

WHEN I click on the new model checkbox

THEN the new model appears in "Modèle(s)" client's column.

5. New Model can be selected as a background sheet

GIVEN I'm in Administration > Configurer les fonds de fiche

WHEN I click on button "Ajouter"

THEN modal "Ajouter"  pops up

AND the new model is shown as selectable in "Choix du modele" box.

6. Submenus for "Edition des FH" if client have rights to access LineTimeTable.

GIVEN I'm a client with LineTimeTable rights AND I'm connected to TimeTable

THEN A chevron is present on "Edition des Fiches Horaires" to indicate a submenu existence

WHEN I click on "Edition des fiches horaires"

AND The "Edition des Fiches Horaires" tab is highlighted

AND the submenu is displayed

AND there is a "Fiches horaires à l'arrêt" entry

AND there is a "Fiches horaires à la ligne" entry

7. Submenu "Fiches horaires à la ligne" entry leads to "Fiches horaires à la ligne" page.

GIVEN I'm a client with LineTimeTable rights AND I'm connected to TimeTable

WHEN I click on "Edition des fiches horaires" > "Fiche horaire à la ligne"

THEN The "Edition des fiches horaires de ligne" "page is open.

AND : Breadcrumb and Title "Edition des fiches horaires de ligne" appear

8. Submenu "Fiches horaires à l'arrêt" entry leads to "Fiches horaires à l'arrêt" page.

GIVEN I'm a client with LineTimeTable rights AND I'm connected to TimeTable

WHEN I click on "Edition des fiches horaires" > "Fiche horaire à l'arrêt"

THEN The "Edition des fiches horaires à l'arrêt" "page is open.

9. No submenu for "Edition des FH" if client doesn't have rights to access 'LineTimeTable'.

GIVEN I'm a client without LineTimeTable rights

AND I'm connected to TimeTable

WHEN I click on "Edition des fiches horaires"

THEN Submenu 'Fiche horaire à l'arrêt' appears

WHEN I click on "Edition des fiches horaires" > "Fiche horaire à l'arrêt"

THEN The "Edition des fiches horaires à l'arrêt" page is open

**Comment by datanel** [comment]
@vpassama the branch feature-58-upload-line-models-and-assignation was created

**Comment by boetien** [comment]
Hi, as discussed with Cyrille earlier today, we'll also need to handle a specific permission for the "Stop point Timetable" feature. That wil allow us to deploy Timetable with either one of the two features or with both.
Can we discuss who handles which permission in tomorrow morning's call ?
Thanks,
Etienne
