### ISSUE TITLE
[Line Timetable ] assign stop_point  to timecard

### ISSUE THREAD

**Issue by bbonnesoeur** [CanalTP/MttBundle#60]
In order to have a synthetic timecard I want to select which stop point will be displayed.

**Tasks**
- add the assignation page 
- handle stops order

**notes**
 add a _displayed_route_stop_point_ table to store stop_point list. Store route ID, stop ID, and display order.

**Acceptance tests**

1. **"Choisir les arrets" button is displayed in "Edition des fiches horaires à la ligne"**
   * GIVEN I'm on "Edition des fiches horaires à la ligne" and I have LineTimeTable rights.
   * WHEN I click on a line in the left pannel
   * THEN the "Choisir les arrêts" button is displayed on the right pannel.

2. **Line StopPoints displayed in chronologic order by "Choisir les arrets" button.**
   * GIVEN I'm on "Edition des fiches horaires à la ligne" > Line
   * AND I have LineTimeTable rights
   * WHEN I click on the "Choisir les arrêts" button
   * THEN All stopPoints of the selected line are displayed
   * AND StopPoints list is sorted by chronologic order

3. **Add one stopPoint in the list**
   * WHEN I click on a stop point (left list) to add it to the right list
   * THEN Stop point appears in the right list and is disabled (grey) in the left list

4. **Line StopAreas list can be re ordered by drag'n drop**
   * GIVEN I'm on "Edition des fiches horaires à la ligne" > Line > "Choisir les arrêts"
   * WHEN I click on a StopPoint
   * AND drag it above another StopPoint 
   * THEN the selected StopPoint goes above the other StopPoint

5. **Line StopAreas list can be saved**
   * GIVEN I'm on "Edition des fiches horaires à la ligne" > Line > "Choisir les arrêts"
   * WHEN I change the StopPoints sorting order
   * AND I click on "Enregistrer" button
   * AND I logout
   * AND I login
   * AND I go back to "Edition des fiches horaires à la ligne" > Line > "Choisir les arrêts"
   * THEN StopArea's sorting order is the same than before I use the "Enregistrer l'ordre" button.

6. **Line's StopPoints list isn't saved without user action**
   * GIVEN I'm on "Edition des fiches horaires à la ligne" > Line > "Choisir les arrêts"
   * WHEN I change the StopPoints sorting order
   * AND I logout
   * AND I login
   * AND I go back to "Edition des fiches horaires à la ligne" > Line > "Choisir les arrêts"
   * THEN the StopPoints list is sorted by chronologic order.

7. **Add all stop Points to the list**
   * WHEN I click on "Ajouter tous les arrêts"
   * THEN All stops are added
 
8. **Remove stop points from the list**
   * WHEN Click on a stop point (list) to remove it from the right list
   * THEN the stop point disappears from the list and isn't disables any more in the left list

**Comment by vpassama** [comment]
Just a word about the stop selection and the tests, 

The selection isn't on StopAreas but on StopPoints (physical stops).

We discussed about the stops' sorting, and we may choose the route schedules sorting instead of the alphabetical sorting. It seems to be easier for the user to scroll down the selection panel and see stops sorted in a chronological way.
